// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const TAB_ID_WINDOW_NAME_KEY = "__pethaven_supabase_tab_id__";

const getTabId = () => {
  const existingTabId = window.name
    .split(";")
    .find((part) => part.startsWith(`${TAB_ID_WINDOW_NAME_KEY}=`))
    ?.split("=")[1];

  if (existingTabId) {
    return existingTabId;
  }

  const nextTabId =
    window.crypto?.randomUUID?.() ??
    `${Date.now()}-${Math.random().toString(16).slice(2)}`;

  window.name = [window.name, `${TAB_ID_WINDOW_NAME_KEY}=${nextTabId}`]
    .filter(Boolean)
    .join(";");

  return nextTabId;
};

const tabScopedSessionStorage = {
  getItem: (key: string) =>
    window.sessionStorage.getItem(`${key}:${getTabId()}`),
  setItem: (key: string, value: string) =>
    window.sessionStorage.setItem(`${key}:${getTabId()}`, value),
  removeItem: (key: string) =>
    window.sessionStorage.removeItem(`${key}:${getTabId()}`),
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: tabScopedSessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
